### ISSUE TITLE
problem with installing proj.4

### ISSUE THREAD

**Issue by eidaraache** [mapbox/aws-lambda-python-packages#2]
Hi, 
I am facing the following problem when I try to install GDAL

 extracting: proj.4-5.0.0/travis/projdocs-private.key.enc  
Running aclocal
Running autoheader
Running libtoolize
autogen.sh: line 33: --force: command not found

  Something went wrong, giving up!

could you please help me ?

**Comment by sgillies** [comment]
This project is finished. I'm going to mark this wontfix and close. You may be interested in https://github.com/RemotePixel/amazonlinux-gdal.
